// DroidX Command Center — premium liquid-glass quick actions
(function(){
  const ACTIONS=[
    ['settings','⚙️','Open Settings','System settings'],['wifi','📶','Wi‑Fi','Wireless settings'],['bluetooth','🔵','Bluetooth','Connected devices'],['location','📍','Location','Location services'],['battery','🔋','Battery','Power settings'],['apps','📱','All Apps','Installed apps'],['display','🖥️','Display','Screen & brightness'],['privacy','🛡️','Privacy','Privacy settings']
  ];
  const KEY='droidx-command-recent-v2';
  const esc=v=>String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));
  const recent=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
  const save=k=>{try{localStorage.setItem(KEY,JSON.stringify([k,...recent().filter(x=>x!==k)].slice(0,5)))}catch{}};
  const run=k=>{save(k);if(typeof window.openAndroidSetting==='function')window.openAndroidSetting(k);else location.hash='settings'};
  const style=document.createElement('style');style.textContent=`
  .command-modal{position:fixed;inset:0;z-index:1500;display:grid;place-items:center;padding:14px}.command-modal[hidden]{display:none!important}.command-backdrop{position:absolute;inset:0;background:rgba(3,6,25,.48);backdrop-filter:blur(16px) saturate(125%);-webkit-backdrop-filter:blur(16px) saturate(125%)}
  .command-dialog{position:relative;width:min(720px,calc(100vw - 24px));max-height:min(82vh,720px);overflow:auto;padding:25px;border-radius:34px!important;background:linear-gradient(145deg,rgba(235,250,255,.19),rgba(100,150,255,.12) 45%,rgba(180,120,255,.11))!important;border:1px solid rgba(225,250,255,.34)!important;box-shadow:0 32px 100px rgba(0,0,35,.48),inset 0 1px 0 rgba(255,255,255,.38)!important;backdrop-filter:blur(30px) saturate(155%);-webkit-backdrop-filter:blur(30px) saturate(155%)}
  .command-dialog:before{content:"";position:absolute;inset:-35%;background:radial-gradient(circle at 30% 20%,rgba(255,255,255,.16),transparent 30%),radial-gradient(circle at 80% 75%,rgba(80,200,255,.13),transparent 32%);pointer-events:none}.command-dialog>*{position:relative}.command-close{position:absolute!important;right:13px;top:13px;width:40px;height:40px;border-radius:50%;border:1px solid rgba(255,255,255,.24);background:rgba(255,255,255,.10);color:#fff;font-size:25px;cursor:pointer;z-index:4;box-shadow:inset 0 1px 0 rgba(255,255,255,.25)}
  .command-dialog h2{margin:8px 48px 7px 0;font-size:clamp(30px,7vw,46px);letter-spacing:-.03em;color:#fff}.command-hint{margin:0 0 18px;color:rgba(245,250,255,.68);font-size:13px}.command-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.command-item{position:relative;width:100%;min-height:76px;display:grid;grid-template-columns:48px minmax(0,1fr) auto;align-items:center;gap:11px;padding:12px;border:1px solid rgba(225,250,255,.20);border-radius:23px;background:linear-gradient(145deg,rgba(255,255,255,.12),rgba(100,150,255,.08));color:#fff;text-align:left;cursor:pointer;box-shadow:inset 0 1px 0 rgba(255,255,255,.22),0 10px 28px rgba(0,20,80,.13);transition:transform .18s ease,background .18s ease,border-color .18s ease;-webkit-tap-highlight-color:transparent}.command-item:hover,.command-item:focus-visible{transform:translateY(-2px);outline:none;background:linear-gradient(145deg,rgba(255,255,255,.18),rgba(110,170,255,.13));border-color:rgba(220,250,255,.38)}.command-item:active{transform:scale(.98)}.command-item>b{width:46px;height:46px;display:grid;place-items:center;border-radius:16px;background:linear-gradient(145deg,rgba(255,255,255,.18),rgba(255,255,255,.06));border:1px solid rgba(255,255,255,.17);font-size:22px;box-shadow:inset 0 1px 0 rgba(255,255,255,.25)}.command-item span{min-width:0;display:grid;gap:4px}.command-item strong{font-size:15px;line-height:1.1}.command-item small{color:rgba(240,247,255,.62);font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.command-item i{font-size:9px;font-style:normal;color:#c8fbff;border:1px solid rgba(160,240,255,.28);background:rgba(120,220,255,.08);padding:4px 7px;border-radius:99px}.command-foot{display:flex;justify-content:space-between;gap:10px;margin-top:16px;color:rgba(235,245,255,.48);font-size:11px}
  @media(max-width:560px){.command-modal{padding:9px}.command-dialog{padding:20px 14px!important;border-radius:28px!important;max-height:86vh}.command-list{grid-template-columns:1fr;gap:9px}.command-item{min-height:66px;border-radius:20px}.command-item>b{width:43px;height:43px}.command-foot{display:none}}
  @media(prefers-reduced-motion:reduce){.command-item{transition:none!important}}
  `;document.head.appendChild(style);
  const modal=document.createElement('div');modal.id='commandCenter';modal.className='command-modal';modal.hidden=true;modal.innerHTML='<div class="command-backdrop"></div><div class="command-dialog glass" role="dialog" aria-modal="true" aria-labelledby="commandTitle"><button class="command-close" type="button" aria-label="Close">×</button><div class="eyebrow">DROIDX COMMAND CENTER</div><h2 id="commandTitle">Quick Actions</h2><p class="command-hint">Fast Android shortcuts — tap any action.</p><div id="commandList" class="command-list"></div><div class="command-foot"><span>Recent actions appear first</span><span>ESC to close</span></div></div>';document.body.appendChild(modal);
  const list=modal.querySelector('#commandList');
  function render(){const r=recent();const ordered=[...r,...ACTIONS.map(x=>x[0]).filter(x=>!r.includes(x))];list.innerHTML=ordered.map(k=>{const x=ACTIONS.find(a=>a[0]===k);if(!x)return '';return `<button class="command-item" type="button" data-key="${esc(x[0])}"><b>${x[1]}</b><span><strong>${esc(x[2])}</strong><small>${esc(x[3])}</small></span>${r.includes(k)?'<i>Recent</i>':''}</button>`}).join('')}
  function open(){render();modal.hidden=false;document.body.classList.add('modal-open');requestAnimationFrame(()=>list.querySelector('.command-item')?.focus())}function close(){modal.hidden=true;document.body.classList.remove('modal-open')}
  list.addEventListener('click',e=>{const b=e.target.closest('.command-item');if(!b)return;const k=b.dataset.key;close();run(k)});modal.querySelector('.command-close').addEventListener('click',close);modal.querySelector('.command-backdrop').addEventListener('click',close);
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden){e.preventDefault();close();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open()}});
  window.DroidXCommand={open,close};document.getElementById('openCommandCenter')?.addEventListener('click',open);
})();