// DroidX: Android Settings shortcut controller + local favorites + PWA install
const ACTIONS={settings:'android.settings.SETTINGS',wifi:'android.settings.WIFI_SETTINGS',bluetooth:'android.settings.BLUETOOTH_SETTINGS',location:'android.settings.LOCATION_SOURCE_SETTINGS',display:'android.settings.DISPLAY_SETTINGS',sound:'android.settings.SOUND_SETTINGS',audio:'android.settings.SOUND_SETTINGS',security:'android.settings.SECURITY_SETTINGS',battery:'android.settings.BATTERY_SAVER_SETTINGS',apps:'android.settings.APPLICATION_SETTINGS',appsettings:'android.settings.MANAGE_APPLICATIONS_SETTINGS',appnotifications:'android.settings.APP_NOTIFICATION_SETTINGS',defaultapps:'android.settings.MANAGE_DEFAULT_APPS_SETTINGS',storage:'android.settings.INTERNAL_STORAGE_SETTINGS',permissions:'android.settings.MANAGE_SPECIAL_APP_ACCESSES',unknownapps:'android.settings.MANAGE_UNKNOWN_APP_SOURCES',specialaccess:'android.settings.MANAGE_SPECIAL_APP_ACCESSES',usage:'android.settings.USAGE_ACCESS_SETTINGS',batteryusage:'android.settings.BATTERY_SAVER_SETTINGS',appsearch:'android.settings.APPLICATION_SETTINGS',manageapps:'android.settings.MANAGE_APPLICATIONS_SETTINGS',language:'android.settings.LOCALE_SETTINGS',datetime:'android.settings.DATE_SETTINGS',home:'android.settings.HOME_SETTINGS',keyboard:'android.settings.INPUT_METHOD_SETTINGS',data:'android.settings.DATA_USAGE_SETTINGS',accessibility:'android.settings.ACCESSIBILITY_SETTINGS',search:'android.settings.SEARCH_SETTINGS',device:'android.settings.DEVICE_INFO_SETTINGS',biometrics:'android.settings.BIOMETRIC_ENROLL',network:'android.settings.WIRELESS_SETTINGS',privacy:'android.settings.PRIVACY_SETTINGS',notifications:'android.settings.APP_NOTIFICATION_SETTINGS'};
const DATA=[['settings','⚙️','Open Settings','System settings'],['wifi','📶','Wi-Fi Settings','Wireless network'],['bluetooth','🔵','Bluetooth Settings','Connected devices'],['location','📍','Location Settings','Location services'],['display','🖥️','Display Settings','Screen & brightness'],['sound','🔊','Sound Settings','Volume & audio'],['security','🔐','Security Settings','Security & privacy'],['battery','🔋','Battery Settings','Power & battery'],['apps','📱','All Apps','Installed apps'],['language','🌐','Language / Locale','Languages & region'],['datetime','📅','Date & Time','Clock & timezone'],['home','🏠','Home / Launcher','Default home app'],['keyboard','⌨️','Keyboard / Input','Input methods'],['data','📊','Data Usage','Network usage'],['accessibility','♿','Accessibility','Accessibility services'],['search','🔍','Search Settings','Device search'],['device','📲','Device Information','About your phone'],['biometrics','🔒','Biometrics','Fingerprint & face'],['appsettings','⚙️','App Settings','Application management'],['appnotifications','🔔','App Notifications','Notification controls'],['defaultapps','🧩','Default Apps','Choose default apps'],['storage','💾','Storage','Storage settings'],['permissions','🔐','App Permissions','Special app access'],['unknownapps','📦','Install Unknown Apps','Special install access'],['specialaccess','🛡️','Special App Access','Advanced app access'],['usage','⏱️','App Usage','Usage controls'],['batteryusage','🔋','App Battery','Power usage controls'],['appsearch','🔎','Search Apps','Find installed apps'],['manageapps','🗂️','Manage Applications','Application manager'],['network','📡','Network Settings','Wireless & mobile network'],['privacy','🛡️','Privacy Settings','Privacy controls'],['notifications','🔔','Notifications','Notification controls'],['audio','🎧','Audio Controls','Sound settings']];
const SETTINGS=DATA.slice(0,18),APPS=DATA.slice(18,30),UTILITIES=[DATA[0],DATA[29],DATA[30],DATA[31],DATA[32]];
const FALLBACK='Your browser/device does not support this shortcut.';const toast=document.getElementById('toast');let toastTimer;
function showToast(message=FALLBACK){if(!toast)return;toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3600)}
function openAndroidSetting(key){const action=ACTIONS[key];if(!action){showToast();return}if(!/Android/i.test(navigator.userAgent)){showToast(FALLBACK);return}saveRecent(key);let failed=true;const onHide=()=>{failed=false;document.removeEventListener('visibilitychange',onHide)};document.addEventListener('visibilitychange',onHide);const timer=setTimeout(()=>{document.removeEventListener('visibilitychange',onHide);if(failed)showToast()},1500);try{window.location.href=`intent:#Intent;action=${action};end`}catch(e){clearTimeout(timer);document.removeEventListener('visibilitychange',onHide);showToast()}}
const STORE='droidx-favorites-v1',RECENT='droidx-recent-v1';
function getStore(key){try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}}
function setStore(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function isFavorite(key){return getStore(STORE).includes(key)}
function toggleFavorite(key){let list=getStore(STORE);list=list.includes(key)?list.filter(x=>x!==key):[key,...list].slice(0,12);setStore(STORE,list);renderAll();showToast(list.includes(key)?'Added to favorites ★':'Removed from favorites')}
function saveRecent(key){const list=[key,...getStore(RECENT).filter(x=>x!==key)].slice(0,6);setStore(RECENT,list);renderFavorites()}
function card(item,compact=false){const [key,icon,name,desc]=item;const el=document.createElement('div');el.className='card'+(compact?' mini-card':'');el.dataset.key=key;el.tabIndex=0;el.innerHTML=`<button class="favorite-btn ${isFavorite(key)?'saved':''}" type="button" aria-label="${isFavorite(key)?'Remove':'Add'} ${name} ${isFavorite(key)?'from':'to'} favorites">${isFavorite(key)?'★':'☆'}</button><b>${icon}</b><span>${name}</span><small>${desc}</small>`;el.addEventListener('click',e=>{if(e.target.closest('.favorite-btn'))return;openAndroidSetting(key)});el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openAndroidSetting(key)}});el.querySelector('.favorite-btn').addEventListener('click',()=>toggleFavorite(key));return el}
function renderGrid(id,items,compact=false){const grid=document.getElementById(id);if(!grid)return;grid.replaceChildren(...items.map(x=>card(x,compact)))}
function renderFavorites(){const grid=document.getElementById('favoriteGrid'),empty=document.getElementById('emptyFavorites'),count=document.getElementById('favoriteCount');if(!grid)return;const fav=getStore(STORE),recent=getStore(RECENT);const favItems=fav.map(k=>DATA.find(x=>x[0]===k)).filter(Boolean);const recentItems=recent.map(k=>DATA.find(x=>x[0]===k)).filter(Boolean).filter(x=>!fav.includes(x[0])).slice(0,4);const items=[...favItems,...recentItems];grid.replaceChildren(...items.map(x=>card(x,true)));if(empty)empty.hidden=items.length>0;if(count)count.textContent=`${favItems.length} favorite${favItems.length===1?'':'s'}${recentItems.length?' · recent':''}`}
function renderAll(){renderGrid('shortcutGrid',SETTINGS);renderGrid('appGrid',APPS);renderGrid('utilityGrid',UTILITIES);renderFavorites();filterShortcuts()}
renderAll();document.querySelectorAll('[data-intent]').forEach(el=>el.addEventListener('click',()=>openAndroidSetting(el.dataset.intent)));document.getElementById('year').textContent=new Date().getFullYear();
const searchInput=document.getElementById('shortcutSearch'),clearSearch=document.getElementById('clearSearch'),shortcutGrid=document.getElementById('shortcutGrid'),shortcutCount=document.getElementById('shortcutCount'),noResults=document.getElementById('noResults');
function filterShortcuts(){const query=(searchInput?.value||'').trim().toLowerCase();let visible=0;[...(shortcutGrid?.querySelectorAll('.card')||[])].forEach(card=>{const match=!query||card.textContent.toLowerCase().includes(query);card.hidden=!match;if(match)visible++});if(shortcutCount)shortcutCount.textContent=query?`${visible} result${visible===1?'':'s'}`:'18 shortcuts';if(noResults)noResults.hidden=visible!==0}
searchInput?.addEventListener('input',filterShortcuts);clearSearch?.addEventListener('click',()=>{if(searchInput){searchInput.value='';filterShortcuts();searchInput.focus()}});
function glassTouch(el,e){const r=el.getBoundingClientRect(),p=e.touches?.[0]||e;el.style.setProperty('--mx',`${((p.clientX-r.left)/r.width)*100}%`);el.style.setProperty('--my',`${((p.clientY-r.top)/r.height)*100}%`)}
document.addEventListener('pointermove',e=>{const el=e.target.closest('.card,.primary,.secondary,.topbar,.hero,.info,.search-box');if(el)glassTouch(el,e)},{passive:true});document.addEventListener('pointerdown',e=>{const el=e.target.closest('.card,.primary,.secondary,.topbar,.hero,.info,.search-box');if(el)el.classList.add('glass-touch')});document.addEventListener('pointerup',e=>{const el=e.target.closest('.card,.primary,.secondary,.topbar,.hero,.info,.search-box');if(el)el.classList.remove('glass-touch')});
const navItems=[...document.querySelectorAll('.bottom-nav .nav-item')];const navSections=['top','favorites','settings','apps','utilities'].map(id=>document.getElementById(id));const observer=new IntersectionObserver(entries=>{const active=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!active)return;const target=active.target.id==='favorites'?'top':active.target.id;const map={top:0,settings:1,apps:2,utilities:3};const i=map[target];if(i!==undefined)navItems.forEach((item,n)=>item.classList.toggle('active',n===i))},{rootMargin:'-35% 0px -50% 0px',threshold:[0,.15,.35,.6]});navSections.forEach(s=>s&&observer.observe(s));
function ensureQuickModal(){if(document.getElementById('quickModal'))return;const modal=document.createElement('div');modal.id='quickModal';modal.className='quick-modal';modal.hidden=true;modal.innerHTML='<div class="quick-backdrop" data-close-quick></div><div class="quick-dialog glass" role="dialog" aria-modal="true" aria-labelledby="quickTitle"><button class="quick-close" type="button" data-close-quick aria-label="Close">×</button><div class="eyebrow">DROIDX QUICK TOOL</div><h2 id="quickTitle">Device Information</h2><div id="quickBody" class="quick-body"></div></div>';document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target.matches('[data-close-quick]'))closeQuickModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeQuickModal()})}
function esc(v){return String(v).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]))}
function openQuickModal(title,html){ensureQuickModal();const m=document.getElementById('quickModal');document.getElementById('quickTitle').textContent=title;document.getElementById('quickBody').innerHTML=html;m.hidden=false;document.body.classList.add('modal-open')}
function closeQuickModal(){const m=document.getElementById('quickModal');if(m){m.hidden=true;document.body.classList.remove('modal-open')}}
function deviceDetails(){const ua=navigator.userAgent;const platform=navigator.platform||'Unknown';const mobile=/Mobi|Android|iPhone|iPad/i.test(ua);const touch=('ontouchstart' in window)||navigator.maxTouchPoints>0;const rows=[['Device type',mobile?'Mobile / Tablet':'Desktop'],['Platform',platform],['Operating system',/Android/i.test(ua)?'Android':/iPhone|iPad/i.test(ua)?'iOS / iPadOS':/Windows/i.test(ua)?'Windows':/Mac OS X/i.test(ua)?'macOS':/Linux/i.test(ua)?'Linux':'Other'],['Screen',`${screen.width} × ${screen.height}`],['Pixel ratio',window.devicePixelRatio||1],['Touch support',touch?'Yes':'No'],['Language',navigator.language||'Unknown'],['Time zone',Intl.DateTimeFormat().resolvedOptions().timeZone||'Unknown']];return rows}
function browserDetails(){const ua=navigator.userAgent;let name='Unknown browser',version='Unknown';const tests=[[/Edg\/([\d.]+)/,'Microsoft Edge'],[/OPR\/([\d.]+)/,'Opera'],[/Chrome\/([\d.]+)/,'Google Chrome'],[/Firefox\/([\d.]+)/,'Mozilla Firefox'],[/Version\/([\d.]+).*Safari\//,'Safari']];for(const [re,n] of tests){const m=ua.match(re);if(m){name=n;version=m[1];break}}return [['Browser',name],['Version',version],['Platform',navigator.platform||'Unknown'],['Online',navigator.onLine?'Yes':'No'],['Cookies',navigator.cookieEnabled?'Enabled':'Disabled']]}
function rowsHtml(rows){return `<div class="quick-list">${rows.map(([a,b])=>`<div><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join('')}</div>`}
function updateOnline(){const online=navigator.onLine;const el=document.getElementById('onlineStatus');if(el){el.textContent=online?'● Online':'● Offline';el.classList.toggle('online',online);el.classList.toggle('offline',!online)}const button=document.getElementById('networkStatus');if(button)button.querySelector('small').textContent=online?'Internet connection available':'No internet connection'}
document.getElementById('deviceInfo')?.addEventListener('click',()=>openQuickModal('Device & Browser Info',`<h3>📱 Device</h3>${rowsHtml(deviceDetails())}<h3>🌐 Browser</h3>${rowsHtml(browserDetails())}`));document.getElementById('networkStatus')?.addEventListener('click',()=>openQuickModal('Network Status',`<div class="network-big ${navigator.onLine?'online':'offline'}">${navigator.onLine?'● ONLINE':'● OFFLINE'}</div><p class="quick-note">DroidX reads the browser's current online state. It does not inspect or store your network credentials.</p>${rowsHtml([['Connection state',navigator.onLine?'Connected':'Disconnected'],['Checked',new Date().toLocaleTimeString()]])}`));document.getElementById('shareDroidX')?.addEventListener('click',async()=>{const data={title:'DroidX',text:'DroidX — Smart Android Shortcuts',url:location.href};try{if(navigator.share){await navigator.share(data);showToast('Share sheet opened ✓')}else{await navigator.clipboard.writeText(location.href);showToast('Link copied — sharing is not supported here')} }catch(e){if(e?.name!=='AbortError')showToast('Sharing cancelled or unavailable')}});document.getElementById('copyDroidX')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);showToast('DroidX link copied ✓')}catch{showToast('Copy is not available in this browser')}});updateOnline();window.addEventListener('online',updateOnline);window.addEventListener('offline',updateOnline);
let deferredInstall=null;const installButton=document.getElementById('installApp');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;if(installButton)installButton.hidden=false});installButton?.addEventListener('click',async()=>{if(!deferredInstall)return;deferredInstall.prompt();try{await deferredInstall.userChoice}catch{}deferredInstall=null;installButton.hidden=true});window.addEventListener('appinstalled',()=>{deferredInstall=null;if(installButton)installButton.hidden=true;showToast('DroidX installed successfully ✓')});
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
